use std::collections::HashMap;

use crate::constants::{LONG_SIZE, SYNC_FRONTIER_ANNOUNCEMENT, SYNC_TX_BATCH};

use super::{ID_LEN, id_hex_to_array};

#[derive(Clone, Copy, Eq, PartialEq)]
pub(crate) enum MessageKind {
    Frontier,
    TxBatch,
    Tx
}

impl MessageKind {
    pub(crate) fn from_payload(payload: &[u8]) -> Self {
        if payload.first() == Some(&SYNC_FRONTIER_ANNOUNCEMENT) {
            Self::Frontier
        } else if payload.first() == Some(&SYNC_TX_BATCH) {
            Self::TxBatch
        } else {
            Self::Tx
        }
    }

    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Frontier => "frontier",
            Self::TxBatch => "tx-batch",
            Self::Tx => "tx"
        }
    }
}

pub(super) struct SyncReader<'a> {
    data: &'a [u8],
    pos: usize
}

impl<'a> SyncReader<'a> {
    pub(super) fn new(data: &'a [u8]) -> Self {
        Self { data, pos: 0 }
    }

    pub(super) fn read_u8(&mut self) -> Option<u8> {
        let byte = *self.data.get(self.pos)?;
        self.pos += 1;
        Some(byte)
    }

    pub(super) fn read_u16(&mut self) -> Option<u16> {
        let bytes = self.read_bytes(2)?;
        Some(u16::from_be_bytes([bytes[0], bytes[1]]))
    }

    pub(super) fn read_group_u64(&mut self, len_code: u8) -> Option<u64> {
        let len = group_u64_len_from_code(len_code)?;
        let bytes = self.read_bytes(len)?;
        let mut value = [0u8; LONG_SIZE as usize];
        value[..len].copy_from_slice(bytes);
        Some(u64::from_le_bytes(value))
    }

    pub(super) fn read_bytes(&mut self, len: usize) -> Option<&'a [u8]> {
        let end = self.pos.checked_add(len)?;
        let bytes = self.data.get(self.pos..end)?;
        self.pos = end;
        Some(bytes)
    }

    pub(super) fn is_done(&self) -> bool {
        self.pos == self.data.len()
    }
}

pub(crate) fn encode_frontier_announcement(entries: Vec<(String, u64)>) -> Vec<u8> {
    let mut entries = entries
        .into_iter()
        .filter_map(|(branch, seq)| {
            let id = id_hex_to_array(&branch)?;
            Some((id, seq))
        })
        .collect::<Vec<_>>();

    if entries.is_empty() {
        return vec![SYNC_FRONTIER_ANNOUNCEMENT];
    }
    if entries.len() > u16::MAX as usize {
        entries.truncate(u16::MAX as usize);
    }

    let count = u16::try_from(entries.len()).ok().unwrap_or(u16::MAX);
    let payload_len = entries
        .iter()
        .map(|(_, seq)| ID_LEN + prefix_varint_len(*seq))
        .sum::<usize>();
    let mut msg = Vec::with_capacity(3 + payload_len);

    msg.push(SYNC_FRONTIER_ANNOUNCEMENT);
    msg.extend_from_slice(&count.to_be_bytes());

    for (id, seq) in entries {
        msg.extend_from_slice(&id);
        encode_prefix_varint(seq, &mut msg);
    }

    msg
}

pub(crate) fn decode_frontier_announcement(payload: &[u8]) -> Option<HashMap<String, u64>> {
    let mut reader = SyncReader::new(payload);

    if reader.read_u8()? != SYNC_FRONTIER_ANNOUNCEMENT {
        return None;
    }

    if reader.is_done() {
        return Some(HashMap::new());
    }

    let count = usize::from(reader.read_u16()?);
    let mut sequences = HashMap::new();

    for _ in 0..count {
        let branch = hex::encode_upper(reader.read_bytes(ID_LEN)?);
        let seq = read_prefix_varint(&mut reader)?;
        sequences.insert(branch, seq);
    }

    reader.is_done().then_some(sequences)
}

pub(crate) fn decode_transaction_batch(payload: &[u8]) -> Option<Vec<Vec<u8>>> {
    if payload.first() != Some(&SYNC_TX_BATCH) {
        return None;
    }

    let mut reader = SyncReader::new(payload);
    reader.read_u8()?;
    let count = usize::from(reader.read_u16()?);
    if count == 0 {
        return None;
    }

    let mut transactions = Vec::with_capacity(count);
    for _ in 0..count {
        let tx_len = usize::from(reader.read_u16()?);
        transactions.push(reader.read_bytes(tx_len)?.to_vec());
    }

    reader.is_done().then_some(transactions)
}

pub(super) fn group_u64_len_code(value: u64) -> u8 {
    let bytes = value.to_le_bytes();
    let len = bytes.iter().rposition(|byte| *byte != 0).map(|index| index + 1).unwrap_or(1);
    (len - 1) as u8
}

pub(super) fn push_group_u64(msg: &mut Vec<u8>, value: u64, len_code: u8) {
    let len = group_u64_len_from_code(len_code)
        .expect("group-u64 length code is generated by group_u64_len_code");
    msg.extend_from_slice(&value.to_le_bytes()[..len]);
}

fn group_u64_len_from_code(len_code: u8) -> Option<usize> {
    if len_code >= LONG_SIZE {
        return None;
    }

    Some(usize::from(len_code) + 1)
}

fn prefix_varint_len(value: u64) -> usize {
    let bits = (u64::BITS - value.leading_zeros()) as usize;
    if bits > 56 {
        9
    } else {
        bits.div_ceil(7).max(1)
    }
}

fn encode_prefix_varint(value: u64, buf: &mut Vec<u8>) {
    let total_len = prefix_varint_len(value);
    if total_len == 9 {
        buf.push(u8::MAX);
        buf.extend_from_slice(&value.to_le_bytes());
        return;
    }

    let first_payload_bits = 8 - total_len;
    let prefix = if total_len == 1 {
        0
    } else {
        u8::MAX << (9 - total_len)
    };
    let payload_mask = if first_payload_bits == 0 {
        0
    } else {
        (1u8 << first_payload_bits) - 1
    };
    buf.push(prefix | ((value as u8) & payload_mask));

    if total_len > 1 {
        let remaining = value >> first_payload_bits;
        buf.extend_from_slice(&remaining.to_le_bytes()[..total_len - 1]);
    }
}

fn read_prefix_varint(reader: &mut SyncReader<'_>) -> Option<u64> {
    let first = reader.read_u8()?;
    let leading_ones = first.leading_ones() as usize;

    let value = if leading_ones == 8 {
        let bytes = reader.read_bytes(8)?;
        let mut raw = [0; 8];
        raw.copy_from_slice(bytes);
        u64::from_le_bytes(raw)
    } else {
        let total_len = leading_ones + 1;
        let first_payload_bits = 8 - total_len;
        let payload_mask = if first_payload_bits == 0 {
            0
        } else {
            (1u8 << first_payload_bits) - 1
        };
        let mut value = u64::from(first & payload_mask);

        if total_len > 1 {
            let bytes = reader.read_bytes(total_len - 1)?;
            let mut remaining = [0; 8];
            remaining[..bytes.len()].copy_from_slice(bytes);
            value |= u64::from_le_bytes(remaining) << first_payload_bits;
        }

        value
    };

    let total_len = if leading_ones == 8 {
        9
    } else {
        leading_ones + 1
    };
    (prefix_varint_len(value) == total_len).then_some(value)
}
